/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokedex;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author aot5238
 */
public class PokeImage extends JPanel
{
    public ImageIcon bulbasaur = new ImageIcon("images/001_Bulbasaur.png");
    public ImageIcon ivysaur = new ImageIcon("images/002_Ivysaur.png");
    public ImageIcon venusaur = new ImageIcon("images/003_Venusaur.png");
    public ImageIcon charmander = new ImageIcon("images/004_Charmander.png");
    public ImageIcon charmeleon = new ImageIcon("images/005_Charmeleon.png");
    public ImageIcon charizard = new ImageIcon("images/006_Charizard.png");
    public ImageIcon squirtle = new ImageIcon("images/007_Squirtle.png");
    public ImageIcon wartortle = new ImageIcon("images/008_Wartortle.png");
    public ImageIcon blastoise = new ImageIcon("images/009_Blastoise.png");
    public ImageIcon caterpie = new ImageIcon("images/010_Caterpie.png");
    public ImageIcon metapod = new ImageIcon("images/011_Metapod.png");
    public ImageIcon butterfree = new ImageIcon("images/012_Butterfree.png");
    public ImageIcon weedle = new ImageIcon("images/013_Weedle.png");
    public ImageIcon kakauna = new ImageIcon("images/014_Kakuna.png");
    public ImageIcon beedrill = new ImageIcon("images/015_Beedrill.png");
    public ImageIcon pidgey = new ImageIcon("images/016_Pidgey.png");
    public ImageIcon pidgeotto = new ImageIcon("images/017_Pidgeotto.png");
    public ImageIcon pidgeot = new ImageIcon("images/018_Pidgeot.png");
    public ImageIcon rattata = new ImageIcon("images/019_Rattata.png");
    public ImageIcon raticate = new ImageIcon("images/020_Raticate.png");
    public ImageIcon spearow = new ImageIcon("images/021_spearow.png");
    public ImageIcon fearow = new ImageIcon("images/022_Fearow.png");
    public ImageIcon ekans = new ImageIcon("images/023_Ekans.png");
    public ImageIcon arbok = new ImageIcon("images/024_Arbok.png");
    public ImageIcon pikachu = new ImageIcon("images/025_Pikachu.png");
    public ImageIcon raichu = new ImageIcon("images/026_Raichu.png");
    public ImageIcon sandshrew = new ImageIcon("images/027_Sandshrew.png");
    public ImageIcon sandslash = new ImageIcon("images/028_Sandslash.png");
    public ImageIcon nidoranf = new ImageIcon("images/029_Nidoran.png");
    public ImageIcon nidorina = new ImageIcon("images/030_Nidorina.png");
    public ImageIcon nidoqueen = new ImageIcon("images/031_Nidoqueen.png");
    public ImageIcon nidoranm = new ImageIcon("images/032_Nidoran.png");
    public ImageIcon nidorino = new ImageIcon("images/033_Nidorino.png");
    public ImageIcon nidoking = new ImageIcon("images/034_Nidoking.png");
    public ImageIcon clefairy = new ImageIcon("images/035_Clefairy.png");
    public ImageIcon clefable = new ImageIcon("images/036_Clefable.png");
    public ImageIcon vulpix = new ImageIcon("images/037_Vulpix.png");
    public ImageIcon ninetales = new ImageIcon("images/038_Ninetales.png");
    public ImageIcon jigglypuff = new ImageIcon("images/039_Jigglypuff.png");
    public ImageIcon wigglytuff = new ImageIcon("images/040_Wigglytuff.png");
    public ImageIcon zubat = new ImageIcon("images/041_Zubat.png");
    public ImageIcon golbat = new ImageIcon("images/042_Golbat.png");
    public ImageIcon oddish = new ImageIcon("images/043_Oddish.png");
    public ImageIcon gloom = new ImageIcon("images/044_Gloom.png");
    public ImageIcon vileplume = new ImageIcon("images/045_Vileplume.png");
    public ImageIcon paras = new ImageIcon("images/046_Paras.png");
    public ImageIcon parasect = new ImageIcon("images/047_Parasect.png");
    public ImageIcon venonat = new ImageIcon("images/048_Venonat.png");
    public ImageIcon venomoth = new ImageIcon("images/049_Venomoth.png");
    public ImageIcon diglett = new ImageIcon("images/050_Diglett.png");
    public ImageIcon dugtrio = new ImageIcon("images/051_Dugtrio.png");
    public ImageIcon meowth = new ImageIcon("images/052_Meowth.png");
    public ImageIcon persian = new ImageIcon("images/053_Persian.png");
    public ImageIcon psyduck = new ImageIcon("images/054_Psyduck.png");
    public ImageIcon golduck = new ImageIcon("images/055_Golduck.png");
    public ImageIcon mankey = new ImageIcon("images/056_Mankey.png");
    public ImageIcon primeape = new ImageIcon("images/057_Primeape.png");
    public ImageIcon growlithe = new ImageIcon("images/058_Growlithe.png");
    public ImageIcon arcanine = new ImageIcon("images/059_Arcanine.png");
    public ImageIcon poliwag = new ImageIcon("images/060_Poliwag.png");
    public ImageIcon poliwhirl = new ImageIcon("images/061_Poliwhirl.png");
    public ImageIcon poliwrath = new ImageIcon("images/062_Poliwrath.png");
    public ImageIcon abra = new ImageIcon("images/063_Abra.png");
    public ImageIcon kadabra = new ImageIcon("images/064_Kadabra.png");
    public ImageIcon alakazam = new ImageIcon("images/065_Alakazam.png");
    public ImageIcon machop = new ImageIcon("images/066_Machop.png");
    public ImageIcon machoke = new ImageIcon("images/067_Machoke.png");
    public ImageIcon machamp = new ImageIcon("images/068_Machamp.png");
    public ImageIcon bellsprout = new ImageIcon("images/069_Bellsprout.png");
    public ImageIcon weepinbell = new ImageIcon("images/070_Weepinbell.png");
    public ImageIcon victreebel = new ImageIcon("images/071_Victreebel.png");
    public ImageIcon tentacool = new ImageIcon("images/072_Tentacool.png");
    public ImageIcon tentacruel = new ImageIcon("images/073_Tentacruel.png");
    public ImageIcon geodude = new ImageIcon("images/074_Geodude.png");
    public ImageIcon graveler = new ImageIcon("images/075_Graveler.png");
    public ImageIcon golem = new ImageIcon("images/076_Golem.png");
    public ImageIcon ponyta = new ImageIcon("images/077_Ponyta.png");
    public ImageIcon rapidash = new ImageIcon("images/078_Rapidash.png");
    public ImageIcon slowpoke = new ImageIcon("images/079_Slowpoke.png");
    public ImageIcon slowbro = new ImageIcon("images/080_Slowbro.png");
    public ImageIcon magnemite = new ImageIcon("images/081_Magnemite.png");
    public ImageIcon magneton = new ImageIcon("images/082_Magneton.png");
    public ImageIcon farfetchd = new ImageIcon("images/083_Farfetch'd.png");
    public ImageIcon doduo = new ImageIcon("images/084_Doduo.png");
    public ImageIcon dodrio = new ImageIcon("images/085_Dodrio.png");
    public ImageIcon seel = new ImageIcon("images/086_Seel.png");
    public ImageIcon dewgong = new ImageIcon("images/087_Dewgong.png");
    public ImageIcon grimer = new ImageIcon("images/088_Grimer.png");
    public ImageIcon muk = new ImageIcon("images/089_Muk.png");
    public ImageIcon shelder = new ImageIcon("images/090_Shellder.png");
    public ImageIcon cloyster = new ImageIcon("images/091_Cloyster.png");
    public ImageIcon gastly = new ImageIcon("images/092_Gastly.png");
    public ImageIcon haunter = new ImageIcon("images/093_Haunter.png");
    public ImageIcon gengar = new ImageIcon("images/094_Gengar.png");
    public ImageIcon onix = new ImageIcon("images/095_Onix.png");
    public ImageIcon drowzee = new ImageIcon("images/096_Drowzee.png");
    public ImageIcon hypno = new ImageIcon("images/097_Hypno.png");
    public ImageIcon krabby = new ImageIcon("images/098_Krabby.png");
    public ImageIcon kingler = new ImageIcon("images/099_Kingler.png");
    public ImageIcon voltorb = new ImageIcon("images/100_Voltorb.png");
    public ImageIcon electrode = new ImageIcon("images/101_Electrode.png");
    public ImageIcon exeggcute = new ImageIcon("images/102_Exeggcute.png");
    public ImageIcon exeggcutor = new ImageIcon("images/103_Exeggutor.png");
    public ImageIcon cubone = new ImageIcon("images/104_Cubone.png");
    public ImageIcon marowak = new ImageIcon("images/105_Marowak.png");
    public ImageIcon hitmonlee = new ImageIcon("images/106_Hitmonlee.png");
    public ImageIcon hitmonchan = new ImageIcon("images/107_Hitmonchan.png");
    public ImageIcon lickitung = new ImageIcon("images/108_Lickitung.png");
    public ImageIcon koffing = new ImageIcon("images/109_Koffing.png");
    public ImageIcon weezing = new ImageIcon("images/110_Weezing.png");
    public ImageIcon rhyhorn = new ImageIcon("images/111_Rhyhorn.png");
    public ImageIcon rhydon = new ImageIcon("images/112_Rhydon.png");
    public ImageIcon chansey = new ImageIcon("images/113_Chansey.png");
    public ImageIcon tangela = new ImageIcon("images/114_Tangela.png");
    public ImageIcon kangaskhan = new ImageIcon("images/115_Kangaskhan.png");
    public ImageIcon horsea = new ImageIcon("images/116_Horsea.png");
    public ImageIcon seadra = new ImageIcon("images/117_Seadra.png");
    public ImageIcon goldeen = new ImageIcon("images/118_Goldeen.png");
    public ImageIcon seaking = new ImageIcon("images/119_Seaking.png");
    public ImageIcon staryu = new ImageIcon("images/120_Staryu.png");
    public ImageIcon starmie = new ImageIcon("images/121_Starmie.png");
    public ImageIcon mrmime = new ImageIcon("images/122_Mr._Mime.png");
    public ImageIcon scyther = new ImageIcon("images/123_Scyther.png");
    public ImageIcon jynx = new ImageIcon("images/124_Jynx.png");
    public ImageIcon electabuzz = new ImageIcon("images/125_Electabuzz.png");
    public ImageIcon magmar = new ImageIcon("images/126_Magmar.png");
    public ImageIcon pinsir = new ImageIcon("images/127_Pinsir.png");
    public ImageIcon tauros = new ImageIcon("images/128_Tauros.png");
    public ImageIcon magikarp = new ImageIcon("images/129_Magikarp.png");
    public ImageIcon gyarados = new ImageIcon("images/130_Gyarados.png");
    public ImageIcon lapras = new ImageIcon("images/131_Lapras.png");
    public ImageIcon ditto = new ImageIcon("images/132_Ditto.png");
    public ImageIcon eevee = new ImageIcon("images/133_Eevee.png");
    public ImageIcon vaporeon = new ImageIcon("images/134_Vaporeon.png");
    public ImageIcon jolteon = new ImageIcon("images/135_Jolteon.png");
    public ImageIcon flareon = new ImageIcon("images/136_Flareon.png");
    public ImageIcon porygon = new ImageIcon("images/137_Porygon.png");
    public ImageIcon omanyte = new ImageIcon("images/138_Omanyte.png");
    public ImageIcon omastar = new ImageIcon("images/139_Omastar.png");
    public ImageIcon kabuto = new ImageIcon("images/140_Kabuto.png");
    public ImageIcon kabutops = new ImageIcon("images/141_Kabutops.png");
    public ImageIcon aerodactyl = new ImageIcon("images/142_Aerodactyl.png");
    public ImageIcon snorlax = new ImageIcon("images/143_Snorlax.png");
    public ImageIcon articuno = new ImageIcon("images/144_Articuno.png");
    public ImageIcon zapdos = new ImageIcon("images/145_Zapdos.png");
    public ImageIcon moltres = new ImageIcon("images/146_Moltres.png");
    public ImageIcon dratini = new ImageIcon("images/147_Dratini.png");
    public ImageIcon dragonair = new ImageIcon("images/148_Dragonair.png");
    public ImageIcon dragonite = new ImageIcon("images/149_Dragonite.png");
    public ImageIcon mewtwo = new ImageIcon("images/150_Mewtwo.png");
    public ImageIcon mew = new ImageIcon("images/151_Mew.png");
    JPanel PokeImage = new JPanel();
    public ImageIcon[] pokemon = new ImageIcon[151];
    public int currentImage = 0;    
    
    public PokeImage()
    {
        setBackground(Color.BLACK);
        //setPreferredSize(new Dimension(250,250));
        
        PokeImage.add(new JLabel(bulbasaur));
        pokemon[0] = bulbasaur;
        pokemon[1] = ivysaur;
        pokemon[2] = venusaur;
        pokemon[3] = charmander;
        pokemon[4] = charmeleon;
        pokemon[5] = charizard;
        pokemon[6] = squirtle;
        pokemon[7] = wartortle;
        pokemon[8] = blastoise;
        pokemon[9] = caterpie;
        pokemon[10] =  metapod;
        pokemon[11] =  butterfree;
        pokemon[12] =  weedle;
        pokemon[13] =  kakauna;
        pokemon[14] =  beedrill;
        pokemon[15] =  pidgey;
        pokemon[16] =  pidgeotto;
        pokemon[17] =  pidgeot;
        pokemon[18] =  rattata;
        pokemon[19] =  raticate;
        pokemon[20] =  spearow;
        pokemon[21] =  fearow;
        pokemon[22] =  ekans;
        pokemon[23] =  arbok;
        pokemon[24] =  pikachu;
        pokemon[25] =  raichu;
        pokemon[26] =  sandshrew;
        pokemon[27] =  sandslash;
        pokemon[28] =  nidoranf;
        pokemon[29] =  nidorina;
        pokemon[30] =  nidoqueen;
        pokemon[31] =  nidoranm;
        pokemon[32] =  nidorino;
        pokemon[33] =  nidoking;
        pokemon[34] =  clefairy;
        pokemon[35] =  clefable;
        pokemon[36] =  vulpix;
        pokemon[37] =  ninetales;
        pokemon[38] =  jigglypuff;
        pokemon[39] =  wigglytuff;
        pokemon[40] =  zubat;
        pokemon[41] =  golbat;
        pokemon[42] =  oddish;
        pokemon[43] =  gloom;
        pokemon[44] =  vileplume;
        pokemon[45] =  paras;
        pokemon[46] =  parasect;
        pokemon[47] =  venonat;
        pokemon[48] =  venomoth;
        pokemon[49] =  diglett;
        pokemon[50] =  dugtrio;
        pokemon[51] =  meowth;
        pokemon[52] =  persian;
        pokemon[53] =  psyduck;
        pokemon[54] =  golduck;
        pokemon[55] =  mankey;
        pokemon[56] =  primeape;
        pokemon[57] =  growlithe;
        pokemon[58] =  arcanine;
        pokemon[59] =  poliwag;
        pokemon[60] =  poliwhirl;
        pokemon[61] =  poliwrath;
        pokemon[62] =  abra;
        pokemon[63] =  kadabra;
        pokemon[64] =  alakazam;
        pokemon[65] =  machop;
        pokemon[66] =  machoke;
        pokemon[67] =  machamp;
        pokemon[68] =  bellsprout;
        pokemon[69] =  weepinbell;
        pokemon[70] =  victreebel;
        pokemon[71] =  tentacool;
        pokemon[72] =  tentacruel;
        pokemon[73] =  geodude;
        pokemon[74] =  graveler;
        pokemon[75] =  golem;
        pokemon[76] =  ponyta;
        pokemon[77] =  rapidash;
        pokemon[78] =  slowpoke;
        pokemon[79] =  slowbro;
        pokemon[80] =  magnemite;
        pokemon[81] =  magneton;
        pokemon[82] =  farfetchd;
        pokemon[83] =  doduo;
        pokemon[84] =  dodrio;
        pokemon[85] =  seel;
        pokemon[86] =  dewgong;
        pokemon[87] =  grimer;
        pokemon[88] =  muk;
        pokemon[89] =  shelder;
        pokemon[90] =  cloyster;
        pokemon[91] =  gastly;
        pokemon[92] =  haunter;
        pokemon[93] =  gengar;
        pokemon[94] =  onix;
        pokemon[95] =  drowzee;
        pokemon[96] =  hypno;
        pokemon[97] =  krabby;
        pokemon[98] =  kingler;
        pokemon[99] =  voltorb;
        pokemon[100] =  electrode;
        pokemon[101] =  exeggcute;
        pokemon[102] =  exeggcutor;
        pokemon[103] =  cubone;
        pokemon[104] =  marowak;
        pokemon[105] =  hitmonlee;
        pokemon[106] =  hitmonchan;
        pokemon[107] =  lickitung;
        pokemon[108] =  koffing;
        pokemon[109] =  weezing;
        pokemon[110] =  rhyhorn;
        pokemon[111] =  rhydon;
        pokemon[112] =  chansey;
        pokemon[113] =  tangela;
        pokemon[114] =  kangaskhan;
        pokemon[115] =  horsea;
        pokemon[116] =  seadra ;
        pokemon[117] =  goldeen;
        pokemon[118] =  seaking;
        pokemon[119] =  staryu;
        pokemon[120] =  starmie;
        pokemon[121] =  mrmime;
        pokemon[122] =  scyther;
        pokemon[123] =  jynx;
        pokemon[124] =  electabuzz;
        pokemon[125] =  magmar;
        pokemon[126] =  pinsir;
        pokemon[127] =  tauros;
        pokemon[128] =  magikarp;
        pokemon[129] =  gyarados;
        pokemon[130] =  lapras;
        pokemon[131] =  ditto;
        pokemon[132] =  eevee;
        pokemon[133] =  vaporeon;
        pokemon[134] =  jolteon;
        pokemon[135] =  flareon;
        pokemon[136] =  porygon;
        pokemon[137] =  omanyte;
        pokemon[138] =  omastar;
        pokemon[139] =  kabuto;
        pokemon[140] =  kabutops;
        pokemon[141] =  aerodactyl;
        pokemon[142] =  snorlax;
        pokemon[143] =  articuno;
        pokemon[144] =  zapdos;
        pokemon[145] =  moltres;
        pokemon[146] =  dratini;
        pokemon[147] =  dragonair;
        pokemon[148] =  dragonite;
        pokemon[149] =  mewtwo;
        pokemon[150] =  mew;

        
        add(PokeImage);
        
    }
    
//    public void paintComponent(Graphics g)
//    {
//        super.paintComponent(g);
//        ImageIcon Icon = new ImageIcon();
//        g.drawImage(Icon.getImage(), 0, 0, this);
//        
//    }
}
