/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokedex;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class PokeDetail extends JPanel
{
    public JLabel bulbasaur = new JLabel ("<html> NUMBER: # 001 <br/> NAME: Bulbasaur <br/> TYPE: Grass/Poison <br/> HONEST NAME: The One No One Ever Picked </html>");
    public JLabel ivysaur = new JLabel ("<html> NUMBER: # 002 <br/> NAME: Ivysaur <br/> TYPE: Grass/Poison <br/> HONEST NAME: Bloomin' Onion </html>");
    public JLabel venusaur = new JLabel ("<html> NUMBER: # 003 <br/> NAME: Venusaur <br/> TYPE: Grass/Poison <br/> HONEST NAME: Plantasaurus Rex </html>");
    public JLabel charmander = new JLabel ("<html> NUMBER: # 004 <br/> NAME: Charmander <br/> TYPE: Fire <br/> HONEST NAME: Oh God My Tail Is On Fire </html>");
    public JLabel charmeleon = new JLabel ("<html> NUMBER: # 005 <br/> NAME: Charmeleon <br/> TYPE: Fire <br/> HONEST NAME: Charma Chameleon </html>");
    public JLabel charizard = new JLabel ("<html> NUMBER: # 006 <br/> NAME: Charizard <br/> TYPE: Fire/Flying <br/> HONEST NAME: Smaug </html>");
    public JLabel squirtle = new JLabel ("<html> NUMBER: # 007 <br/> NAME: Squirtle <br/> TYPE: Water <br/> HONEST NAME: Squirter </html>");
    public JLabel wartortle = new JLabel ("<html> NUMBER: # 008 <br/> NAME: Wartortle <br/> TYPE: Water <br/> HONEST NAME: Leonardo </html>");
    public JLabel blastoise = new JLabel ("<html> NUMBER: # 009 <br/> NAME: Blastoise <br/> TYPE: Water <br/> HONEST NAME: Water Bowser </html>");
    public JLabel caterpie = new JLabel ("<html> NUMBER: # 010 <br/> NAME: Caterpie <br/> TYPE: Bug <br/> HONEST NAME: The Very Hungry Caterpillar </html>");
    public JLabel metapod = new JLabel ("<html> NUMBER: # 011 <br/> NAME: Metapod <br/> TYPE: Bug <br/> HONEST NAME: What Doesn't Kill You <br/>Makes You Harden </html>");
    public JLabel butterfree = new JLabel ("<html> NUMBER: # 012 <br/> NAME: Butterfree <br/> TYPE: Bug/Flying <br/> HONEST NAME: Lower Back Tattoo </html>");
    public JLabel weedle = new JLabel ("<html> NUMBER: # 013 <br/> NAME: Weedle <br/> TYPE: Bug/Poison <br/> HONEST NAME: Smokin' Weedle </html>");
    public JLabel kakauna = new JLabel ("<html> NUMBER: # 014 <br/> NAME: Kakauna <br/> TYPE: Bug/Poison <br/> HONEST NAME: Kakuna Matata </html>");
    public JLabel beedrill = new JLabel ("<html> NUMBER: # 015 <br/> NAME: Beedrill <br/> TYPE: Bug/Poison <br/> HONEST NAME: Mohammed A-Bee </html>");
    public JLabel pidgey = new JLabel ("<html> NUMBER: # 016 <br/> NAME: Pidgey <br/> TYPE: Normal/Flying <br/> HONEST NAME: A Bird </html>");
    public JLabel pidgeotto = new JLabel ("<html> NUMBER: # 017 <br/> NAME: Pidgeotto <br/> TYPE: Normal/Flying <br/> HONEST NAME: A Bigger Bird </html>");
    public JLabel pidgeot = new JLabel ("<html> NUMBER: # 018 <br/> NAME: Pidgeot <br/> TYPE: Normal/Flying <br/> HONEST NAME: A Slightly Bigger <br/>Bird Than That </html>");
    public JLabel rattata = new JLabel ("<html> NUMBER: # 019 <br/> NAME: Rattata <br/> TYPE: Normal <br/> HONEST NAME: Ratatat </html>");
    public JLabel raticate = new JLabel ("<html> NUMBER: # 020 <br/> NAME: Raticate <br/> TYPE: Normal <br/> HONEST NAME: Deadmau5 </html>");
    public JLabel spearow = new JLabel ("<html> NUMBER: # 021 <br/> NAME: Spearow <br/> TYPE: Normal/Flying <br/> HONEST NAME: Britney Spearow </html>");
    public JLabel fearow = new JLabel ("<html> NUMBER: # 022 <br/> NAME: Fearow <br/> TYPE: Normal/Flying <br/> HONEST NAME: Fearow To The Knee </html>");
    public JLabel ekans = new JLabel ("<html> NUMBER: # 023 <br/> NAME: Ekans <br/> TYPE: Poison <br/> HONEST NAME: Snake Spelled Backwards </html>");
    public JLabel arbok = new JLabel ("<html> NUMBER: # 024 <br/> NAME: Arbok <br/> TYPE: Poison <br/> HONEST NAME: Kobra Kai </html>");
    public JLabel pikachu = new JLabel ("<html> NUMBER: # 025 <br/> NAME: Pikachu <br/> TYPE: Electric <br/> HONEST NAME: Japanese Mickey </html>");
    public JLabel raichu = new JLabel ("<html> NUMBER: # 026 <br/> NAME: Raichu <br/> TYPE: Electric <br/> HONEST NAME: Wrongchu </html>");
    public JLabel sandshrew = new JLabel ("<html> NUMBER: # 027 <br/> NAME: Sandshrew <br/> TYPE: Ground <br/> HONEST NAME: Taming Of The Sandshrew </html>");
    public JLabel sandslash = new JLabel ("<html> NUMBER: # 028 <br/> NAME: Sandslash <br/> TYPE: Ground <br/> HONEST NAME: Hurricane Sandy </html>");
    public JLabel nidoranf = new JLabel ("<html> NUMBER: # 029 <br/> NAME: Nidoran <br/> TYPE: Poison <br/> HONEST NAME: Jailbait </html>");
    public JLabel nidorina = new JLabel ("<html> NUMBER: # 030 <br/> NAME: Nidorina <br/> TYPE: Poison <br/> HONEST NAME: Barely Legal </html>");
    public JLabel nidoqueen = new JLabel ("<html> NUMBER: # 031 <br/> NAME: Nidoqueen <br/> TYPE: Poison/Ground <br/> HONEST NAME: Milf </html>");
    public JLabel nidoranm = new JLabel ("<html> NUMBER: # 032 <br/> NAME: Nidoran <br/> TYPE: Poison <br/> HONEST NAME: Pedobait </html>");
    public JLabel nidorino = new JLabel ("<html> NUMBER: # 033 <br/> NAME: Nidorino <br/> TYPE: Poison <br/> HONEST NAME: Boytoy </html>");
    public JLabel nidoking = new JLabel ("<html> NUMBER: # 034 <br/> NAME: Nidoking <br/> TYPE: Poison/Ground <br/> HONEST NAME: Dilf </html>");
    public JLabel clefairy = new JLabel ("<html> NUMBER: # 035 <br/> NAME: Clefairy <br/> TYPE: Fairy <br/> HONEST NAME: Lame Kirby </html>");
    public JLabel clefable = new JLabel ("<html> NUMBER: # 036 <br/> NAME: Clefable <br/> TYPE: Fairy <br/> HONEST NAME: Queefable </html>");
    public JLabel vulpix = new JLabel ("<html> NUMBER: # 037 <br/> NAME: Vulpix <br/> TYPE: Fire <br/> HONEST NAME: What Does The Vulpix Say </html>");
    public JLabel ninetales = new JLabel ("<html> NUMBER: # 038 <br/> NAME: Ninetales <br/> TYPE: Fire <br/> HONEST NAME: Miles 'Ninetales' Prower </html>");
    public JLabel jigglypuff = new JLabel ("<html> NUMBER: # 039 <br/> NAME: Jigglypuff <br/> TYPE: Normal/Fairy <br/> HONEST NAME: Lana Del Rey </html>");
    public JLabel wigglytuff = new JLabel ("<html> NUMBER: # 040 <br/> NAME: Wigglytuff <br/> TYPE: Normal/Fairy <br/> HONEST NAME: Mama June </html>");
    public JLabel zubat = new JLabel ("<html> NUMBER: # 041 <br/> NAME: Zubat <br/> TYPE: Poison/Flying <br/> HONEST NAME: Cave Herpes </html>");
    public JLabel golbat = new JLabel ("<html> NUMBER: # 042 <br/> NAME: Golbat <br/> TYPE: Poison/Flying <br/> HONEST NAME: Edward Cullen </html>");
    public JLabel oddish = new JLabel ("<html> NUMBER: # 043 <br/> NAME: Oddish <br/> TYPE: Grass/Poison <br/> HONEST NAME: Turnup For What </html>");
    public JLabel gloom = new JLabel ("<html> NUMBER: # 044 <br/> NAME: Gloom <br/> TYPE: Grass/Poison <br/> HONEST NAME: Orlando Gloom </html>");
    public JLabel vileplume = new JLabel ("<html> NUMBER: # 045 <br/> NAME: Vileplume <br/> TYPE: Grass/Poison <br/> HONEST NAME: Black Toad </html>");
    public JLabel paras = new JLabel ("<html> NUMBER: # 046 <br/> NAME: Paras <br/> TYPE: Bug/Grass <br/> HONEST NAME: Paras Hilton </html>");
    public JLabel parasect = new JLabel ("<html> NUMBER: # 047 <br/> NAME: Parasect <br/> TYPE: Bug/Grass <br/> HONEST NAME: The Flood </html>");
    public JLabel venonat = new JLabel ("<html> NUMBER: # 048 <br/> NAME: Venonat <br/> TYPE: Bug/Poison <br/> HONEST NAME: Evil Furby </html>");
    public JLabel venomoth = new JLabel ("<html> NUMBER: # 049 <br/> NAME: Venomoth <br/> TYPE: Bug/Poison <br/> HONEST NAME: Mothra </html>");
    public JLabel diglett = new JLabel ("<html> NUMBER: # 050 <br/> NAME: Diglett <br/> TYPE: Ground <br/> HONEST NAME: Dicklett </html>");
    public JLabel dugtrio = new JLabel ("<html> NUMBER: # 051 <br/> NAME: Dugtrio <br/> TYPE: Ground <br/> HONEST NAME: Three Little Dickletts </html>");
    public JLabel meowth = new JLabel ("<html> NUMBER: # 052 <br/> NAME: Meowth <br/> TYPE: Normal <br/> HONEST NAME: Grumpy Cat </html>");
    public JLabel persian = new JLabel ("<html> NUMBER: # 053 <br/> NAME: Persian <br/> TYPE: Normal <br/> HONEST NAME: Kim Catdashian </html>");
    public JLabel psyduck = new JLabel ("<html> NUMBER: # 054 <br/> NAME: Psyduck <br/> TYPE: Water <br/> HONEST NAME: Gangnam Style </html>");
    public JLabel golduck = new JLabel ("<html> NUMBER: # 055 <br/> NAME: Golduck <br/> TYPE: Water <br/> HONEST NAME: Goldwing Duck </html>");
    public JLabel mankey = new JLabel ("<html> NUMBER: # 056 <br/> NAME: Mankey <br/> TYPE: Fighting <br/> HONEST NAME: Spankey My Mankey </html>");
    public JLabel primeape = new JLabel ("<html> NUMBER: # 057 <br/> NAME: Primeape <br/> TYPE: Fighting <br/> HONEST NAME: Planet Of The Primeapes </html>");
    public JLabel growlithe = new JLabel ("<html> NUMBER: # 058 <br/> NAME: Growlithe <br/> TYPE: Fire <br/> HONEST NAME: Macklemore </html>");
    public JLabel arcanine = new JLabel ("<html> NUMBER: # 059 <br/> NAME: Arcanine <br/> TYPE: Fire <br/> HONEST NAME: R-K-9 </html>");
    public JLabel poliwag = new JLabel ("<html> NUMBER: # 060 <br/> NAME: Poliwag <br/> TYPE: Water <br/> HONEST NAME: Spin Art </html>");
    public JLabel poliwhirl = new JLabel ("<html> NUMBER: # 061 <br/> NAME: Poliwhirl <br/> TYPE: Water <br/> HONEST NAME: This Is Your Brain </html>");
    public JLabel poliwrath = new JLabel ("<html> NUMBER: # 062 <br/> NAME: Poliwrath <br/> TYPE: Water/Fighting <br/> HONEST NAME: This Is Your Brain On Drugs </html>");
    public JLabel abra = new JLabel ("<html> NUMBER: # 063 <br/> NAME: Abra <br/> TYPE: Psychic <br/> HONEST NAME: There Is No Spoon </html>");
    public JLabel kadabra = new JLabel ("<html> NUMBER: # 064 <br/> NAME: Kadabra <br/> TYPE: Psychic <br/> HONEST NAME: There Is One Spoon </html>");
    public JLabel alakazam = new JLabel ("<html> NUMBER: # 065 <br/> NAME: Alakazam <br/> TYPE: Psychic <br/> HONEST NAME: There Are Two Spoons </html>");
    public JLabel machop = new JLabel ("<html> NUMBER: # 066 <br/> NAME: Machop <br/> TYPE: Fighting <br/> HONEST NAME: Judo Chop </html>");
    public JLabel machoke = new JLabel ("<html> NUMBER: # 067 <br/> NAME: Machoke <br/> TYPE: Fighting <br/> HONEST NAME: Machop On Roids </html>");
    public JLabel machamp = new JLabel ("<html> NUMBER: # 068 <br/> NAME: Machamp <br/> TYPE: Fighting <br/> HONEST NAME: Goro </html>");
    public JLabel bellsprout = new JLabel ("<html> NUMBER: # 069 <br/> NAME: Bellsprout <br/> TYPE: Grass/Poison <br/> HONEST NAME: Plant Vs. Zombies </html>");
    public JLabel weepinbell = new JLabel ("<html> NUMBER: # 070 <br/> NAME: Weepinbell <br/> TYPE: Grass/Poison <br/> HONEST NAME: Nature's Fleshlight </html>");
    public JLabel victreebel = new JLabel ("<html> NUMBER: # 071 <br/> NAME: Victreebel <br/> TYPE: Grass/Poison <br/> HONEST NAME: Venus Dicktrap </html>");
    public JLabel tentacool = new JLabel ("<html> NUMBER: # 072 <br/> NAME: Tentacool <br/> TYPE: Water/Poison <br/> HONEST NAME: Japanese Lunch </html>");
    public JLabel tentacruel = new JLabel ("<html> NUMBER: # 073 <br/> NAME: Tentacruel <br/> TYPE: Water/Poison <br/> HONEST NAME: Japanese Pornstar </html>");
    public JLabel geodude = new JLabel ("<html> NUMBER: # 074 <br/> NAME: Geodude <br/> TYPE: Rock/Ground <br/> HONEST NAME: Racky Ballboa </html>");
    public JLabel graveler = new JLabel ("<html> NUMBER: # 075 <br/> NAME: Graveler <br/> TYPE: Rock/Ground <br/> HONEST NAME: Pet Rock </html>");
    public JLabel golem = new JLabel ("<html> NUMBER: # 076 <br/> NAME: Golem <br/> TYPE: Rock/Ground <br/> HONEST NAME: Angry Golf Ball </html>");
    public JLabel ponyta = new JLabel ("<html> NUMBER: # 077 <br/> NAME: Ponyta <br/> TYPE: Fire <br/> HONEST NAME: My Little Ponyta </html>");
    public JLabel rapidash = new JLabel ("<html> NUMBER: # 078 <br/> NAME: Rapidash <br/> TYPE: Fire <br/> HONEST NAME: This Horse Is On Fiyaaa </html>");
    public JLabel slowpoke = new JLabel ("<html> NUMBER: # 079 <br/> NAME: Slowpoke <br/> TYPE: Water/Psychic <br/> HONEST NAME: duhhhh </html>");
    public JLabel slowbro = new JLabel ("<html> NUMBER: # 080 <br/> NAME: Slowbro <br/> TYPE: Water/Psychic <br/> HONEST NAME: derrrrrrr </html>");
    public JLabel magnemite = new JLabel ("<html> NUMBER: # 081 <br/> NAME: Magnemite <br/> TYPE: Electric/Steel <br/> HONEST NAME: Junior Science Fair Project </html>");
    public JLabel magneton = new JLabel ("<html> NUMBER: # 082 <br/> NAME: Magneton <br/> TYPE: Electric/Steel <br/> HONEST NAME: Magneto's Balls </html>");
    public JLabel farfetchd = new JLabel ("<html> NUMBER: # 083 <br/> NAME: Farfetchd <br/> TYPE: Normal/Flying <br/> HONEST NAME: A Bird With A Unibrow <br/>Holding A Green Onion </html>");
    public JLabel doduo = new JLabel ("<html> NUMBER: # 084 <br/> NAME: Doduo <br/> TYPE: Normal/Flying <br/> HONEST NAME: Doodoooh </html>");
    public JLabel dodrio = new JLabel ("<html> NUMBER: # 085 <br/> NAME: Dodrio <br/> TYPE: Normal/Flying <br/> HONEST NAME: Cerbirdus </html>");
    public JLabel seel = new JLabel ("<html> NUMBER: # 086 <br/> NAME: Seel <br/> TYPE: Water <br/> HONEST NAME: Kiss From A Rose </html>");
    public JLabel dewgong = new JLabel ("<html> NUMBER: # 087 <br/> NAME: Dewgong <br/> TYPE: Water/Ice <br/> HONEST NAME: Mountain Dewgong </html>");
    public JLabel grimer = new JLabel ("<html> NUMBER: # 088 <br/> NAME: Grimer <br/> TYPE: Poison <br/> HONEST NAME: Grimace </html>");
    public JLabel muk = new JLabel ("<html> NUMBER: # 089 <br/> NAME: Muk <br/> TYPE: Poison <br/> HONEST NAME: Kum Spelled Backwards </html>");
    public JLabel shelder = new JLabel ("<html> NUMBER: # 090 <br/> NAME: Shelder <br/> TYPE: Water <br/> HONEST NAME: Shelldon Cooper </html>");
    public JLabel cloyster = new JLabel ("<html> NUMBER: # 091 <br/> NAME: Cloyster <br/> TYPE: Water/Ice <br/> HONEST NAME: Haunted Vagina </html>");
    public JLabel gastly = new JLabel ("<html> NUMBER: # 092 <br/> NAME: Gastly <br/> TYPE: Ghost/Poison <br/> HONEST NAME: Rick Gastly </html>");
    public JLabel haunter = new JLabel ("<html> NUMBER: # 093 <br/> NAME: Haunter <br/> TYPE: Ghost/Poison <br/> HONEST NAME: Dead Wolverine </html>");
    public JLabel gengar = new JLabel ("<html> NUMBER: # 094 <br/> NAME: Gengar <br/> TYPE: Ghost/Poison <br/> HONEST NAME: Evil Stitch </html>");
    public JLabel onix = new JLabel ("<html> NUMBER: # 095 <br/> NAME: Onix <br/> TYPE: Rock/Ground <br/> HONEST NAME: Hooked On Onix </html>");
    public JLabel drowzee = new JLabel ("<html> NUMBER: # 096 <br/> NAME: Drowzee <br/> TYPE: Psychic <br/> HONEST NAME: Nyquil </html>");
    public JLabel hypno = new JLabel ("<html> NUMBER: # 097 <br/> NAME: Hypno <br/> TYPE: Psychic <br/> HONEST NAME: Date Rapist </html>");
    public JLabel krabby = new JLabel ("<html> NUMBER: # 098 <br/> NAME: Krabby <br/> TYPE: Water <br/> HONEST NAME: Krabby Patty </html>");
    public JLabel kingler = new JLabel ("<html> NUMBER: # 099 <br/> NAME: Kingler <br/> TYPE: Water <br/> HONEST NAME: Stage 5 Kingler </html>");
    public JLabel voltorb = new JLabel ("<html> NUMBER: # 100 <br/> NAME: Voltorb <br/> TYPE: Electric <br/> HONEST NAME: A Pokeball </html>");
    public JLabel electrode = new JLabel ("<html> NUMBER: # 101 <br/> NAME: Electrode <br/> TYPE: Electric <br/> HONEST NAME: Al Qaeda </html>");
    public JLabel exeggcute = new JLabel ("<html> NUMBER: # 102 <br/> NAME: Exeggcute <br/> TYPE: Grass/Psychic <br/> HONEST NAME: Exeggcute Order 66 </html>");
    public JLabel exeggcutor = new JLabel ("<html> NUMBER: # 103 <br/> NAME: Exeggcutor <br/> TYPE: Grass/Psychic <br/> HONEST NAME: Smelly Pineapple </html>");
    public JLabel cubone = new JLabel ("<html> NUMBER: # 104 <br/> NAME: Cubone <br/> TYPE: Ground <br/> HONEST NAME: Mommy Issues </html>");
    public JLabel marowak = new JLabel ("<html> NUMBER: # 105 <br/> NAME: Marowak <br/> TYPE: Ground <br/> HONEST NAME: Jack Skullington </html>");
    public JLabel hitmonlee = new JLabel ("<html> NUMBER: # 106 <br/> NAME: Hitmonlee <br/> TYPE: Fighting <br/> HONEST NAME: Bruce Lee </html>");
    public JLabel hitmonchan = new JLabel ("<html> NUMBER: # 107 <br/> NAME: Hitmonchan <br/> TYPE: Fighting <br/> HONEST NAME: Jacqui Chan </html>");
    public JLabel lickitung = new JLabel ("<html> NUMBER: # 108 <br/> NAME: Lickitung <br/> TYPE: Normal <br/> HONEST NAME: Girl's Best Friend </html>");
    public JLabel koffing = new JLabel ("<html> NUMBER: # 109 <br/> NAME: Koffing <br/> TYPE: Poison <br/> HONEST NAME: Bronchitis </html>");
    public JLabel weezing = new JLabel ("<html> NUMBER: # 110 <br/> NAME: Weezing <br/> TYPE: Poison <br/> HONEST NAME: Lung Cancer </html>");
    public JLabel rhyhorn = new JLabel ("<html> NUMBER: # 111 <br/> NAME: Rhyhorn <br/> TYPE: Ground/Rock <br/> HONEST NAME: Ryback </html>");
    public JLabel rhydon = new JLabel ("<html> NUMBER: # 112 <br/> NAME: Rhydon <br/> TYPE: Ground/Rock <br/> HONEST NAME: Rhydon't </html>");
    public JLabel chansey = new JLabel ("<html> NUMBER: # 113 <br/> NAME: Chansey <br/> TYPE: Normal <br/> HONEST NAME: Teen Mom </html>");
    public JLabel tangela = new JLabel ("<html> NUMBER: # 114 <br/> NAME: Tangela <br/> TYPE: Grass <br/> HONEST NAME: Walking Spaghetti Monster </html>");
    public JLabel kangaskhan = new JLabel ("<html> NUMBER: # 115 <br/> NAME: Kangaskhan <br/> TYPE: Normal <br/> HONEST NAME: Krangas Khan </html>");
    public JLabel horsea = new JLabel ("<html> NUMBER: # 116 <br/> NAME: Horsea <br/> TYPE: Water <br/> HONEST NAME: Water Birdo </html>");
    public JLabel seadra = new JLabel ("<html> NUMBER: # 117 <br/> NAME: Seadra <br/> TYPE: Water <br/> HONEST NAME: Hail Seadra </html>");
    public JLabel goldeen = new JLabel ("<html> NUMBER: # 118 <br/> NAME: Goldeen <br/> TYPE: Water <br/> HONEST NAME: Finding Goldeen </html>");
    public JLabel seaking = new JLabel ("<html> NUMBER: # 119 <br/> NAME: Seaking <br/> TYPE: Water <br/> HONEST NAME: Desperately Seaking Susan </html>");
    public JLabel staryu = new JLabel ("<html> NUMBER: # 120 <br/> NAME: Staryu <br/> TYPE: Water <br/> HONEST NAME: Patrick </html>");
    public JLabel starmie = new JLabel ("<html> NUMBER: # 121 <br/> NAME: Starmie <br/> TYPE: Water/Psychic <br/> HONEST NAME: Jewish Starmie </html>");
    public JLabel mrmime = new JLabel ("<html> NUMBER: # 122 <br/> NAME: Mrmime <br/> TYPE: Psychic/Fairy <br/> HONEST NAME: Hi, I'm A <br/>Registered Sex Offender </html>");
    public JLabel scyther = new JLabel ("<html> NUMBER: # 123 <br/> NAME: Scyther <br/> TYPE: Bug/Flying <br/> HONEST NAME: Rock, Paper, Scyther </html>");
    public JLabel jynx = new JLabel ("<html> NUMBER: # 124 <br/> NAME: Jynx <br/> TYPE: Ice/Psychic <br/> HONEST NAME: Nicki Minaj </html>");
    public JLabel electabuzz = new JLabel ("<html> NUMBER: # 125 <br/> NAME: Electabuzz <br/> TYPE: Electric <br/> HONEST NAME: Buzzfeed </html>");
    public JLabel magmar = new JLabel ("<html> NUMBER: # 126 <br/> NAME: Magmar <br/> TYPE: Fire <br/> HONEST NAME: Flaming Butthead </html>");
    public JLabel pinsir = new JLabel ("<html> NUMBER: # 127 <br/> NAME: Pinsir <br/> TYPE: Bug <br/> HONEST NAME: Like A Pinsir </html>");
    public JLabel tauros = new JLabel ("<html> NUMBER: # 128 <br/> NAME: Tauros <br/> TYPE: Normal <br/> HONEST NAME: Bull**** </html>");
    public JLabel magikarp = new JLabel ("<html> NUMBER: # 129 <br/> NAME: Magikarp <br/> TYPE: Water <br/> HONEST NAME: Not Living Up <br/>To Your Potential </html>");
    public JLabel gyarados = new JLabel ("<html> NUMBER: # 130 <br/> NAME: Gyarados <br/> TYPE: Water/Flying <br/> HONEST NAME: Gyary Busey </html>");
    public JLabel lapras = new JLabel ("<html> NUMBER: # 131 <br/> NAME: Lapras <br/> TYPE: Water/Ice <br/> HONEST NAME: The Loch Ness Monster </html>");
    public JLabel ditto = new JLabel ("<html> NUMBER: # 132 <br/> NAME: Ditto <br/> TYPE: Normal <br/> HONEST NAME: Whatever You Want Me To Be </html>");
    public JLabel eevee = new JLabel ("<html> NUMBER: # 133 <br/> NAME: Eevee <br/> TYPE: Normal <br/> HONEST NAME: Eevee Spelled Backwards </html>");
    public JLabel vaporeon = new JLabel ("<html> NUMBER: # 134 <br/> NAME: Vaporeon <br/> TYPE: Water <br/> HONEST NAME: Catfish </html>");
    public JLabel jolteon = new JLabel ("<html> NUMBER: # 135 <br/> NAME: Jolteon <br/> TYPE: Electric <br/> HONEST NAME: Rabbichu </html>");
    public JLabel flareon = new JLabel ("<html> NUMBER: # 136 <br/> NAME: Flareon <br/> TYPE: Fire <br/> HONEST NAME: Firecrotch </html>");
    public JLabel porygon = new JLabel ("<html> NUMBER: # 137 <br/> NAME: Porygon <br/> TYPE: Normal <br/> HONEST NAME: Asian Polygon </html>");
    public JLabel omanyte = new JLabel ("<html> NUMBER: # 138 <br/> NAME: Omanyte <br/> TYPE: Rock/Water <br/> HONEST NAME: Praise Helix </html>");
    public JLabel omastar = new JLabel ("<html> NUMBER: # 139 <br/> NAME: Omastar <br/> TYPE: Rock/Water <br/> HONEST NAME: Baby Cthulu </html>");
    public JLabel kabuto = new JLabel ("<html> NUMBER: # 140 <br/> NAME: Kabuto <br/> TYPE: Rock/Water <br/> HONEST NAME: Headcrab </html>");
    public JLabel kabutops = new JLabel ("<html> NUMBER: # 141 <br/> NAME: Kabutops <br/> TYPE: Rock/Water <br/> HONEST NAME: Edward Scytherhands </html>");
    public JLabel aerodactyl = new JLabel ("<html> NUMBER: # 142 <br/> NAME: Aerodactyl <br/> TYPE: Rock/Flying <br/> HONEST NAME: Sarah Jurassica Parker </html>");
    public JLabel snorlax = new JLabel ("<html> NUMBER: # 143 <br/> NAME: Snorlax <br/> TYPE: Normal <br/> HONEST NAME: Diabetus </html>");
    public JLabel articuno = new JLabel ("<html> NUMBER: # 144 <br/> NAME: Articuno <br/> TYPE: Ice/Flying <br/> HONEST NAME: Blue Jay Leno </html>");
    public JLabel zapdos = new JLabel ("<html> NUMBER: # 145 <br/> NAME: Zapdos <br/> TYPE: Electric/Flying <br/> HONEST NAME: Shoes In Spanish </html>");
    public JLabel moltres = new JLabel ("<html> NUMBER: # 146 <br/> NAME: Moltres <br/> TYPE: Fire/Flying <br/> HONEST NAME: This Bird Is On Fiyaaa </html>");
    public JLabel dratini = new JLabel ("<html> NUMBER: # 147 <br/> NAME: Dratini <br/> TYPE: Dragon <br/> HONEST NAME: Drapeeny </html>");
    public JLabel dragonair = new JLabel ("<html> NUMBER: # 148 <br/> NAME: Dragonair <br/> TYPE: Dragon <br/> HONEST NAME: Puff The Magic Dragonair </html>");
    public JLabel dragonite = new JLabel ("<html> NUMBER: # 149 <br/> NAME: Dragonite <br/> TYPE: Dragon/Flying <br/> HONEST NAME: Chawizawd </html>");
    public JLabel mewtwo = new JLabel ("<html> NUMBER: # 150 <br/> NAME: Mewtwo <br/> TYPE: Psychic <br/> HONEST NAME: Buu Two </html>");
    public JLabel mew = new JLabel ("<html> NUMBER: # 151 <br/> NAME: Mew <br/> TYPE: Psychic <br/> HONEST NAME: Space Fetus </html>");



    JPanel PokeDetail = new JPanel();
    public JLabel[] pokemon = new JLabel[151];
    public int currentDetail = 0;    
    
    public PokeDetail()
    {
        setBackground(Color.BLACK);
        //setPreferredSize(new Dimension(275,275));
        bulbasaur.setPreferredSize(new Dimension(250,250));
        
        PokeDetail.add(bulbasaur);
        pokemon[0] = bulbasaur;
        pokemon[1] = ivysaur;
        pokemon[2] = venusaur;
        pokemon[3] = charmander;
        pokemon[4] = charmeleon;
        pokemon[5] = charizard;
        pokemon[6] = squirtle;
        pokemon[7] = wartortle;
        pokemon[8] = blastoise;
        pokemon[9] = caterpie;
        pokemon[10] =  metapod;
        pokemon[11] =  butterfree;
        pokemon[12] =  weedle;
        pokemon[13] =  kakauna;
        pokemon[14] =  beedrill;
        pokemon[15] =  pidgey;
        pokemon[16] =  pidgeotto;
        pokemon[17] =  pidgeot;
        pokemon[18] =  rattata;
        pokemon[19] =  raticate;
        pokemon[20] =  spearow;
        pokemon[21] =  fearow;
        pokemon[22] =  ekans;
        pokemon[23] =  arbok;
        pokemon[24] =  pikachu;
        pokemon[25] =  raichu;
        pokemon[26] =  sandshrew;
        pokemon[27] =  sandslash;
        pokemon[28] =  nidoranf;
        pokemon[29] =  nidorina;
        pokemon[30] =  nidoqueen;
        pokemon[31] =  nidoranm;
        pokemon[32] =  nidorino;
        pokemon[33] =  nidoking;
        pokemon[34] =  clefairy;
        pokemon[35] =  clefable;
        pokemon[36] =  vulpix;
        pokemon[37] =  ninetales;
        pokemon[38] =  jigglypuff;
        pokemon[39] =  wigglytuff;
        pokemon[40] =  zubat;
        pokemon[41] =  golbat;
        pokemon[42] =  oddish;
        pokemon[43] =  gloom;
        pokemon[44] =  vileplume;
        pokemon[45] =  paras;
        pokemon[46] =  parasect;
        pokemon[47] =  venonat;
        pokemon[48] =  venomoth;
        pokemon[49] =  diglett;
        pokemon[50] =  dugtrio;
        pokemon[51] =  meowth;
        pokemon[52] =  persian;
        pokemon[53] =  psyduck;
        pokemon[54] =  golduck;
        pokemon[55] =  mankey;
        pokemon[56] =  primeape;
        pokemon[57] =  growlithe;
        pokemon[58] =  arcanine;
        pokemon[59] =  poliwag;
        pokemon[60] =  poliwhirl;
        pokemon[61] =  poliwrath;
        pokemon[62] =  abra;
        pokemon[63] =  kadabra;
        pokemon[64] =  alakazam;
        pokemon[65] =  machop;
        pokemon[66] =  machoke;
        pokemon[67] =  machamp;
        pokemon[68] =  bellsprout;
        pokemon[69] =  weepinbell;
        pokemon[70] =  victreebel;
        pokemon[71] =  tentacool;
        pokemon[72] =  tentacruel;
        pokemon[73] =  geodude;
        pokemon[74] =  graveler;
        pokemon[75] =  golem;
        pokemon[76] =  ponyta;
        pokemon[77] =  rapidash;
        pokemon[78] =  slowpoke;
        pokemon[79] =  slowbro;
        pokemon[80] =  magnemite;
        pokemon[81] =  magneton;
        pokemon[82] =  farfetchd;
        pokemon[83] =  doduo;
        pokemon[84] =  dodrio;
        pokemon[85] =  seel;
        pokemon[86] =  dewgong;
        pokemon[87] =  grimer;
        pokemon[88] =  muk;
        pokemon[89] =  shelder;
        pokemon[90] =  cloyster;
        pokemon[91] =  gastly;
        pokemon[92] =  haunter;
        pokemon[93] =  gengar;
        pokemon[94] =  onix;
        pokemon[95] =  drowzee;
        pokemon[96] =  hypno;
        pokemon[97] =  krabby;
        pokemon[98] =  kingler;
        pokemon[99] =  voltorb;
        pokemon[100] =  electrode;
        pokemon[101] =  exeggcute;
        pokemon[102] =  exeggcutor;
        pokemon[103] =  cubone;
        pokemon[104] =  marowak;
        pokemon[105] =  hitmonlee;
        pokemon[106] =  hitmonchan;
        pokemon[107] =  lickitung;
        pokemon[108] =  koffing;
        pokemon[109] =  weezing;
        pokemon[110] =  rhyhorn;
        pokemon[111] =  rhydon;
        pokemon[112] =  chansey;
        pokemon[113] =  tangela;
        pokemon[114] =  kangaskhan;
        pokemon[115] =  horsea;
        pokemon[116] =  seadra ;
        pokemon[117] =  goldeen;
        pokemon[118] =  seaking;
        pokemon[119] =  staryu;
        pokemon[120] =  starmie;
        pokemon[121] =  mrmime;
        pokemon[122] =  scyther;
        pokemon[123] =  jynx;
        pokemon[124] =  electabuzz;
        pokemon[125] =  magmar;
        pokemon[126] =  pinsir;
        pokemon[127] =  tauros;
        pokemon[128] =  magikarp;
        pokemon[129] =  gyarados;
        pokemon[130] =  lapras;
        pokemon[131] =  ditto;
        pokemon[132] =  eevee;
        pokemon[133] =  vaporeon;
        pokemon[134] =  jolteon;
        pokemon[135] =  flareon;
        pokemon[136] =  porygon;
        pokemon[137] =  omanyte;
        pokemon[138] =  omastar;
        pokemon[139] =  kabuto;
        pokemon[140] =  kabutops;
        pokemon[141] =  aerodactyl;
        pokemon[142] =  snorlax;
        pokemon[143] =  articuno;
        pokemon[144] =  zapdos;
        pokemon[145] =  moltres;
        pokemon[146] =  dratini;
        pokemon[147] =  dragonair;
        pokemon[148] =  dragonite;
        pokemon[149] =  mewtwo;
        pokemon[150] =  mew;
        
        add(PokeDetail);
        
    }
    
}
